server:
  port: 8889
logging:
  path: logs
  file: mylog.log
spring:
  application:
    name: mytTest
  datasource:
    data-username:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/course
      username: root
      password: zhao0522
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

